name: Build APK and Windows

on:
  workflow_dispatch:

jobs:

  android:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: zulu
          java-version: "17"

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: "3.22.0"

      - name: Get Packages
        run: flutter pub get

      - name: Recreate Android Folder
        run: |
          rm -rf android
          flutter create --platforms=android .

      - name: Get Packages Again
        run: flutter pub get

      - name: Build APK
        run: flutter build apk --release

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: app-release
          path: build/app/outputs/flutter-apk/app-release.apk

  windows:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: "3.22.0"

      - name: Enable Windows
        run: flutter config --enable-windows-desktop

      - name: Get Packages
        run: flutter pub get

      - name: Create Windows Platform
        run: flutter create --platforms=windows .

      - name: Build Windows
        run: flutter build windows --release

      - name: Zip Windows Build
        shell: powershell
        run: |
          Compress-Archive `
          -Path build/windows/x64/runner/Release/* `
          -DestinationPath build/windows/x64/runner/windows-release.zip

      - name: Upload Windows ZIP
        uses: actions/upload-artifact@v4
        with:
          name: windows-release
          path: build/windows/x64/runner/windows-release.zip
